-- SelectPlayersPokerRakeBetsStmt.sql
--
-- #DBA_REVIEWED #SRE-39369 AlexSlobidker 2022.Main.09

-- TIMEFROM = 2023-05-21-00.00.00
-- TIMETO	= 2023-06-20-23.59.59
-- uiids	= 55454630
SELECT   
  U.USERINTID
 ,SUM( BIGINT( DEC(H.POTCHIPS)/DEC(H.POTSIZE)*DEC(H.RAKESIZE)*1000000.0 +.5 )/1000000 + (CASE WHEN UHC.FLAGS = 1 THEN UHC.RAKE ELSE 0 END) ) AS RAKE
 ,SUM( BIGINT( h.POTCHIPS ) ) AS BETS
 , CURRENCY
FROM HANDS_USERSINHAND H  
JOIN USERS U ON U.USERID = H.USERID
LEFT JOIN USERSINHANDCASHOUT UHC ON H.HANDID = UHC.HANDID AND H.USERID = UHC.USERID
WHERE H.FINISHED BETWEEN '${TIMEFROM}$' AND CAST('${TIMETO}$' AS TIMESTAMP) - 1 MICROSECOND --upper limit is exclusive
-- 0 - REAL_CHIPS, 3 - BLITZ_REAL_CHIPS
 AND H.ISPLAYMONEY IN (0,3) AND H.POTCHIPS>0 AND H.LICENSEMASK_EX = '4000000000' -- LicenceBitmask_CAON
 and u.userintid in ((${uiids}$))
GROUP BY USERINTID, CURRENCY
ORDER BY USERINTID
;