SELECT UC.UPDATEID,UC.UPDATEDFIELD,UC.UPDATETYPE,UC.USERINTID,UC.ADMININTID,UC.WHEN,UC.OLDVALUE,UC.NEWVALUE,UC.APPLOGINID
FROM USERCHANGES UC
JOIN USERS U ON UC.USERINTID=U.USERINTID
JOIN USERFIRSTTIMEEVENTS FTE ON UC.USERINTID=FTE.USERINTID AND U.LICENSEID=FTE.LICENSEID
WHERE U.LICENSEID=131072
 AND UC.WHEN >= FTE.WHEN
 AND UC.WHEN BETWEEN ? AND ?
 AND UC.UPDATEDFIELD IN (1,2,3,5,6,7,9,10,11,12,27,28,34,48)
ORDER BY UC.USERINTID,UC.WHEN,UC.UPDATEID;
