-- SelectXcGamesCompletedForPeriodStmt.sql
--
WITH RMCOMPLETEDGAMES AS
(
  SELECT
    G.GAMEID
   ,G.USERINTID
   ,G.XCLOGINID
   ,G.TABLEID
   ,G.TABLETYPEID
   ,G.GAMETYPEID
   ,G.ISPLAYMONEY
   ,G.CURRENCY
   ,G.RESERVEDFUNDS
   ,G.FLAGS
   ,G.RESTOREGAMEID
   ,G.IPADDR
   ,G.PSLOGINID
   ,G.XCSTARTED
   ,G.PSSTARTED
   ,G.XCCOMPLETED
   ,G.PSCOMPLETED
   ,G.STATUS
   ,G.UNRESOLVEDBET
   ,G.LASTHANDID
   ,G.SELFLIMIT
   ,G.TERMCODE
   ,G.ERRCODE
   ,G.VARIANTTYPE
   ,G.MINBET
   ,G.USERROLLID
   ,G.ROLLRESERVEDFUNDS
   ,G.ROLLUNRESOLVEDBET
   ,G.SPECIALAMOUNT
   ,G.ALLOCATED
   ,G.BRANDID
   ,G.APPLOGINID
   ,G.LASTHANDSTARTED
   ,G.UNRESOLVEDWIN
   ,G.ROLLUNRESOLVEDWIN
   ,U.LICENSEID
   ,G.ROLLALLOCATED
   ,G.JPUNRESOLVEDWIN
   -- insert new XcGames columns here
  FROM XCGAMES G
  JOIN USERFIRSTTIMEEVENTS UFTE ON G.USERINTID=UFTE.USERINTID
  JOIN USERS U ON G.USERINTID=U.USERINTID AND U.LICENSEID=UFTE.LICENSEID
	AND (${excludeTestAccounts}$ = 0
			or
			(
				bitand(U.privileges, 128) = 0 -- privAdmin
				and bitand(U.privileges2, 512+2305843009213693952+33554432+2251799813685248) = 0 -- priv2PSRelated+priv2NjTesting+priv2BetaTester+priv2BizAccount)
			)
		)
  WHERE U.LICENSEID=${LICENSE_ID}$ AND UFTE.WHEN <= G.PSCOMPLETED
AND G.ISPLAYMONEY=0 AND G.PSCOMPLETED BETWEEN '${start}$' AND '${end}$'
)
SELECT
    G.GAMEID
   ,G.USERINTID
   ,G.XCLOGINID
   ,G.TABLEID
   ,G.TABLETYPEID
   ,G.GAMETYPEID
   ,G.ISPLAYMONEY
   ,G.CURRENCY
   ,G.RESERVEDFUNDS
   ,G.FLAGS
   ,G.RESTOREGAMEID
   ,G.IPADDR
   ,G.PSLOGINID
   ,G.XCSTARTED
   ,G.PSSTARTED
   ,G.XCCOMPLETED
   ,G.PSCOMPLETED
   ,G.STATUS
   ,G.UNRESOLVEDBET
   ,G.LASTHANDID
   ,G.SELFLIMIT
   ,G.TERMCODE
   ,G.ERRCODE
   ,G.VARIANTTYPE
   ,G.MINBET
   ,G.USERROLLID
   ,G.ROLLRESERVEDFUNDS
   ,G.ROLLUNRESOLVEDBET
   ,G.SPECIALAMOUNT
   ,G.ALLOCATED
   ,G.BRANDID
   ,G.APPLOGINID
   ,G.LASTHANDSTARTED
   ,G.UNRESOLVEDWIN
   ,G.ROLLUNRESOLVEDWIN
   ,G.LICENSEID
   ,G.ROLLALLOCATED
   ,G.JPUNRESOLVEDWIN

   -- insert new XcGames columns here
   ,VALUE((SELECT COUNT(DISTINCT HANDID) FROM XCTRANS WHERE GAMEID = G.GAMEID AND ((TRANSTYPE = 1 AND DELTAGAME <> 0) OR (TRANSTYPE IN (1, 2) AND BITAND(FLAGS,64) <> 0)) AND ERRCODE = 0),0)  HANDSCOUNT
   ,VALUE((SELECT COUNT FROM XCTRANS WHERE GAMEID = G.GAMEID AND TRANSTYPE IN (1, 2) AND ERRCODE = 0),0)                                HANDSTRANSCOUNT
   ,VALUE((SELECT SUM(BIGINT(DELTAGAME)) FROM XCTRANS WHERE GAMEID = G.GAMEID AND TRANSTYPE = 1 AND ERRCODE = 0), 0)                    GAMEBETS
   ,VALUE((SELECT SUM(BIGINT(DELTAGAME)) FROM XCTRANS WHERE GAMEID = G.GAMEID AND TRANSTYPE = 2 AND ERRCODE = 0), 0)                    GAMEREWARDS
   ,VALUE((SELECT SUM(TOTALCONTRIB) FROM XCGAMEJACKPOTS WHERE GAMEID = G.GAMEID),0)                                                     JACKPOTTOTALCONTRIB
   ,VALUE((SELECT SUM(TOTALWIN) FROM XCGAMEJACKPOTS WHERE GAMEID = G.GAMEID),0)                                                         JACKPOTTOTALWIN
FROM RMCOMPLETEDGAMES G
WHERE G.STATUS <> 9 -- PYR-188112: exclude purged games (eXcGameStatus_AdminForceRemoved)
ORDER BY CURRENCY
;
