--- SelectRmokUserChangesForPeriodStmt --
SELECT
  UC.UPDATEID
 ,UC.UPDATEDFIELD
 ,UC.UPDATETYPE
 ,UC.USERINTID
 ,UC.ADMININTID
 ,UC.WHEN
 ,UC.OLDVALUE
 ,UC.NEWVALUE
 ,UC.APPLOGINID 
FROM USERCHANGES UC 
JOIN USERS U ON UC.USERINTID=U.USERINTID 
JOIN USERFIRSTTIMEEVENTS FTE ON UC.USERINTID=FTE.USERINTID AND U.LICENSEID=FTE.LICENSEID 
WHERE U.LICENSEID=131072 and UC.USERINTID=${userintid}$
 AND UC.WHEN >= FTE.WHEN
 AND UC.WHEN BETWEEN '${PTmidnight}$' and '${ReportTime}$'
 AND UC.UPDATEDFIELD IN (12,28,43,9,1,2,3,6,5,7,10,34,27)
ORDER BY UC.USERINTID,UC.WHEN,UC.UPDATEID
;
