--- SelectRmokUserPropChangesForPeriodStmt --
WITH H AS 
(
 SELECT
  UPA.*
 ,(SELECT UPA2.WHENCHANGED
   FROM USERPROPAUDIT UPA2
   WHERE UPA2.USERINTID=FTE.USERINTID AND UPA2.PROPERTYID=UPA.PROPERTYID AND UPA2.WHENCHANGED<UPA.WHENCHANGED
   ORDER BY 1 DESC FETCH FIRST 1 ROWS ONLY
  ) AS PREV_WHENCHANGED
 FROM USERPROPAUDIT UPA
 JOIN USERS U ON UPA.USERINTID=U.USERINTID
 JOIN USERFIRSTTIMEEVENTS FTE ON UPA.USERINTID+0=FTE.USERINTID AND U.LICENSEID=FTE.LICENSEID
 WHERE U.LICENSEID=131072 and U.USERINTID=${userintid}$
   AND UPA.WHENCHANGED>=FTE.WHEN
   AND UPA.WHENCHANGED BETWEEN '${PTmidnight}$' and '${ReportTime}$'
   AND UPA.PROPERTYID IN (6,33,53,129,132)
) 
, H2 AS 
(
 SELECT
  H.*
 ,UPA.RECORDID     AS RECORDID_PREV
 ,UPA.ADMININTID   AS ADMININTID_PREV
 ,UPA.COMMENT      AS COMMENT_PREV
 ,UPA.PROPERTYINT  AS PROPERTYINT_PREV
 ,UPA.PROPERTYSTR  AS PROPERTYSTR_PREV
 ,UPA.PROPERTYWHEN AS PROPERTYWHEN_PREV
 ,UPA.ACTION       AS ACTION_PREV
 ,UPA.APPLOGINID   AS APPLOGINID_PREV
 ,UPA.WHENCHANGED  AS WHENCHANGED_PREV
 ,ROW_NUMBER() OVER(PARTITION BY H.USERINTID,H.PROPERTYID,UPA.WHENCHANGED ORDER BY UPA.RECORDID DESC) AS NUM
 FROM H LEFT JOIN USERPROPAUDIT UPA ON H.USERINTID=UPA.USERINTID AND H.PROPERTYID=UPA.PROPERTYID AND H.PREV_WHENCHANGED=UPA.WHENCHANGED
) 
SELECT
  RECORDID
 ,ADMININTID
 ,COMMENT
 ,USERINTID
 ,PROPERTYID
 ,PROPERTYINT
 ,PROPERTYSTR
 ,PROPERTYWHEN
 ,ACTION
 ,APPLOGINID
 ,WHENCHANGED
 ,RECORDID_PREV
 ,ADMININTID_PREV
 ,COMMENT_PREV
 ,PROPERTYINT_PREV
 ,PROPERTYSTR_PREV
 ,PROPERTYWHEN_PREV
 ,ACTION_PREV
 ,APPLOGINID_PREV
 ,WHENCHANGED_PREV 
FROM H2 
WHERE NUM=1 
ORDER BY USERINTID,WHENCHANGED,RECORDID
;
