-- db2 -vtf C:\Users\mingtungl\sql\query.sql -z C:\Users\mingtungl\out\results.txt > null
SELECT UC.UPDATEID,UC.UPDATEDFIELD,UC.UPDATETYPE,UC.USERINTID,UC.ADMININTID,UC.WHEN,UC.OLDVALUE,UC.NEWVALUE,UC.APPLOGINID
FROM USERCHANGES UC
JOIN USERS U ON UC.USERINTID=U.USERINTID
JOIN USERFIRSTTIMEEVENTS FTE ON UC.USERINTID=FTE.USERINTID AND U.LICENSEID=FTE.LICENSEID
WHERE U.LICENSEID=131072
  AND UC.WHEN >= FTE.WHEN
  --AND UC.WHEN BETWEEN ? AND ?
  AND UC.WHEN BETWEEN '2021-10-07 00:00:00' AND cast('2021-10-08 00:00:00' as TIMESTAMP) - 1 microsecond
  --AND UC.UPDATEDFIELD IN (1,2,3,5,6,7,9,10,11,12,27,28,34,48)
  AND UC.UPDATEDFIELD IN (11,12)
  --AND U.userintid in (124360749)
ORDER BY UC.USERINTID,UC.WHEN,UC.UPDATEID;
